[package]
name = "dash-mpd-core"
version = "0.1.0"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "Parse and serialize MPD manifests for MPEG-DASH or WebM-DASH media streaming"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-core"
license = "MIT"
keywords = ["MPD", "DASH", "MPEG"]
categories = ["multimedia::video", "parser-implementations"]
publish = true
edition = "2021"


[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_path_to_error = "0.1.20"
quick-xml = { version = "0.42.0", features = ["serialize", "overlapped-lists"] }
chrono = { version = "0.4.45", features = ["serde"] }
num-traits = "0.2.19"
iso8601 = "0.6.5"
regex = { version = "1.13.1", default-features = false, features = ["std", "unicode-perl"] }
thiserror = "2.0.20"
url = "2.5.8"
serde_with = { version = "3.23.0" }
serde_ignored = { version = "0.1.14", optional = true }
tracing = { version = "0.1.44", features = ["attributes", "std"], optional = true }


[dev-dependencies]
clap = "4.5.60"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "time", "macros"] }
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "blocking", "cookies", "gzip"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "local-time", "ansi", "tracing-log"] }
tempfile = { version = "3.27.0" }
proptest = "1.11.0"
anyhow = "1.0.104"
roxmltree = "0.21.1"
approx = "0.5.1"
time = { version = "0.3.54", features = ["macros"] }
pretty_assertions = "1.4.1"


[features]
default = ["log", "scte35"]
scte35 = []
log = ["dep:tracing"]
warn_ignored_elements = ["dep:serde_ignored", "log"]
