on: [push]

name: build/linux

jobs:
  check:
    name: dash-mpd-core check/nightly
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - uses: taiki-e/install-action@cargo-hack
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils
          cargo check
          cargo hack check --feature-powerset --no-dev-deps

  test:
    name: dash-mpd-core test/stable
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v2

      - name: Run tests
        run: |
          RUST_LOG=info cargo test --jobs 1 -- --show-output --test-threads=1
          cargo run --example serialize
          cargo run --example pprint_bbc_adaptive
