on: [push]

name: macos

jobs:
  check-macos:
    name: dash-mpd-core check/macos
    runs-on: macos-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --feature-powerset --no-dev-deps

    
  build-macos:
    name: dash-mpd-core build/macos
    runs-on: macos-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build


  # Not using actions-rust-lang/setup-rust-toolchain because for some incomprehensible reason it
  # does not work ("cargo not found")
  test-macos:
    name: dash-mpd-core test/macos
    runs-on: macos-latest
    timeout-minutes: 100
    needs: check-macos
    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0
      - run: |
          brew update
          brew upgrade || true
          brew install libxml2
          brew install rust
          cargo test --jobs 1 --verbose -- --show-output --test-threads=1
