on: [push]

name: windows

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 150
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2.33.0
      with:
        path-type: inherit
        update: true
        install: base-devel autotools mingw-w64-x86_64-toolchain mingw-w64-x86_64-rust mingw-w64-ucrt-x86_64-gcc

    - uses: taiki-e/install-action@cargo-hack

    # Note: this also installs the xmllint executable that we need for the serialization tests.
    - name: install xsltproc
      run: choco install --yes --limit-output -–no-progress xsltproc

    - run: cargo hack check --feature-powerset --no-dev-deps
      shell: msys2 {0}

    - run: cargo build
      shell: msys2 {0}

    - run: cargo test --verbose --no-run
      shell: msys2 {0}

    - run: cargo test -- --show-output --test-threads=1
      shell: msys2 {0}
